/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef SHADER_H_
# define SHADER_H_
# define VAR_COLOR "r"
# define VAR_ITIME "f"

const char *shader_frag =
 "#version 400\n"
 "vec2 m=vec2(2560,1440);"
 "float v=10000.;"
 "uniform float f;"
 "out vec3 r;"
 "vec3 n(vec3 m,vec3 v)"
 "{"
   "float f=cos(v.x),r=sin(v.x);"
   "mat3 i=mat3(vec3(1,0,0),vec3(0,f,-r),vec3(0,r,f));"
   "f=cos(v.y);"
   "r=sin(v.y);"
   "i*=mat3(vec3(f,0,r),vec3(0,1,0),vec3(-r,0,f));"
   "f=cos(v.z);"
   "r=sin(v.z);"
   "return i*mat3(vec3(f,-r,0),vec3(r,f,0),vec3(0,0,1))*m;"
 "}"
 "float n(vec3 v,vec3 r,float m)"
 "{"
   "vec3 f=abs(v)-r;"
   "return length(max(f,0.))+min(max(f.x,max(f.y,f.z)),0.)-m;"
 "}"
 "float x(float v,float f,float m)"
 "{"
   "float r=max(m-abs(v-f),0.);"
   "return min(v,f)-r*r*.25/m;"
 "}"
 "float n(vec3 v)"
 "{"
   "vec3 m=n(v,vec3(1.5,0.,0.)),r=n(v,vec3(1,f,sin(f*.5)*.5));"
   "float i=n(m-vec3(0.,0.,1.5),vec3(20.,20,.01),.1),s=n(r+vec3(0.,.5,0.),vec3(.375),.1);"
   "return x(i,s,1.);"
 "}"
 "vec3 x(vec3 v)"
 "{"
   "mat3 f=mat3(v,v,v)-mat3(.001);"
   "return normalize(n(v)-vec3(n(f[0]),n(f[1]),n(f[2])));"
 "}"
 "float e(vec3 v,vec3 f,float m)"
 "{"
   "return(dot(v,normalize(f))*.5+.5)*m;"
 "}"
 "float e(vec3 v,vec3 f,vec3 m,float r)"
 "{"
   "vec3 i=reflect(normalize(f),v);"
   "return pow(max(dot(m,i),0.),128.)*r;"
 "}"
 "float e(vec3 v,vec3 f)"
 "{"
   "float r=1.-abs(length(v-f))/100.;"
   "return pow(r,32.)*1.5;"
 "}"
 "float e(in vec3 v,in vec3 f,float m,float r,float i)"
 "{"
   "float x=1.,s=1e+20;"
   "for(float z=m;z<r;)"
     "{"
       "float e=n(v+f*z);"
       "if(e<.0001)"
         "return 0.;"
       "float p=e*e/(2.*s),y=sqrt(e*e-p*p);"
       "x=min(x,i*y/max(0.,z-p));"
       "s=e;"
       "z+=e;"
     "}"
   "return x;"
 "}"
 "void main()"
 "{"
   "vec2 v=gl_FragCoord.xy/m.xy-.5;"
   "v.x/=m.y/m.x;"
   "vec3 f=vec3(0.,0.,-3.5),i=f,s=normalize(vec3(v,1.));"
   "float p=0.;"
   "bool z=false;"
   "while(i.z<20.)"
     "{"
       "float l=n(i);"
       "if(l<.0001)"
         "{"
           "z=true;"
           "break;"
         "}"
       "i+=s*l;"
     "}"
   "float l=length(f-i);"
   "if(z)"
     "{"
       "p=length(i*10.);"
       "vec3 y=x(i),d=vec3(1,.5,-.25);"
       "float t=e(i,d)*e(y,d,.25)+e(y,d,s,.9);"
       "r=vec3(t)+vec3(.1,.4,.1);"
       "vec3 a=f+l*s;"
       "r=mix(vec3(0.),r,e(a,normalize(d),.01,10.,20.)*.25+.75);"
     "}"
   "r*=mix(r,vec3(1.,1.,1.),1.-exp(-.1*pow(l,128.)));"
   "r-=l*.05;"
 "}";

#endif // SHADER_H_
